# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias up="sudo apt update && sudo apt -y upgrade"
alias lsa="ls -a"
alias upg="sudo apt upgrade"
alias upt="sudo apt update"
alias ins="sudo apt install"
alias rem="sudo apt remove"
alias pur="sudo apt purge"
alias auto="sudo apt autoremove"
alias sn="sudo nano"
alias sd="sudo systemctl"
alias sds="sudo systemctl status"
alias sde="sudo systemctl enable"
alias sdst="sudo systemctl start"
alias snsp="sudo systemctl stop"
alias sndis="sudo systemctl disable"
